spring:
  application:
    name: live-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # url: jdbc:shardingsphere:classpath:db-sharding.yaml
    url: jdbc:shardingsphere:nacos:127.0.0.1:8848:live-user-shardingjdbc.yaml
    hikari:
      pool-name: user-pool
      minimum-idle: 15
      maximum-pool-size: 300
      connection-timeout: 4000
      max-lifetime: 60000
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      lettuce:
        pool:
          min-idle: 10
          max-active: 50
          max-idle: 20
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://127.0.0.1:8848
  server: true
  protocol:
    name: dubbo
    port: 9090

rocketmq:
  producer:
    name-srv: 127.0.0.1:9876
    send-time-out: 3000
    retry-times: 3
    group-name: ${spring.application.name}
  consumer:
    name-srv: 127.0.0.1:9876
    group-name: ${spring.application.name}
