spring:
  application:
    name: live-msg-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:8808/live_msg?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    hikari:
      minimum-idle: 15
      maximum-pool-size: 200
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      lettuce:
        pool:
          min-idle: 10
          max-active: 50
          max-idle: 20
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 9092
